MVCVoertuig/Models/ErrorViewModel.cs
namespace MVCVoertuig.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCVoertuig/Models/Voertuig.cs
using MVCVoertuig.CustomValidations;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVCVoertuig.Models
{
    public class Voertuig
    {
        public int VoertuigId { get; set; }

        [Required]
        [StringLength(100)]
        public string Merk { get; set; }

        [Required]
        [StringLength(100)]
        public string MerkType { get; set; }

        [Required]
        [CustomBouwjaarValidation]
        public int Bouwjaar { get; set; }

        [Required]
        [Range(0,5000000)]
        public int Km { get; set; }

        [Required]
        [Column(TypeName= "decimal(8,2)")]
        public decimal VerkoopPrijs { get; set; }

        public bool AanwezigInShowroom { get; set; }

    }
}

MVCVoertuig/Components/HeaderMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVCVoertuig.Data;
using MVCVoertuig.Models;

namespace MVCVoertuig.Components
{
    public class HeaderMenuViewComponent : ViewComponent
    {
        private VoertuigDbContext _context;
        public HeaderMenuViewComponent(VoertuigDbContext context)
        {
            _context = context;
        }


        public IViewComponentResult Invoke()
        {
            var list = _context.Voertuigen
                .Select(x => x.Merk)
                .Distinct()
                .OrderBy(x => x);

            return View(list);
        }

    }
}

MVCVoertuig/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVCVoertuig.Models;

namespace MVCVoertuig.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCVoertuig/Controllers/VoertuigController.cs
using Microsoft.AspNetCore.Mvc;
using MVCVoertuig.Data;
using MVCVoertuig.Models;

namespace MVCVoertuig.Controllers
{
    public class VoertuigController : Controller
    {
        private VoertuigDbContext _context;
        public VoertuigController(VoertuigDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var list = _context.Voertuigen;
            return View(list);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Voertuig v)
        {
            _context.Voertuigen.Add(v);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult Merk(string merk)
        {
            ViewBag.Merk = merk;
            return View(_context.Voertuigen.Where(x => x.Merk == merk));
        }
    }
}

MVCVoertuig/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<car-info></car-info>

MVCVoertuig/Views/Shared/Components/HeaderMenu/Default.cshtml
@model IEnumerable<string>


@foreach(var merkVoertuig in Model)
{
	<a class="btn btn-primary link-warning" asp-controller="Voertuig" asp-action="Merk" asp-route-merk="@merkVoertuig">@merkVoertuig</a>
}

MVCVoertuig/Views/Shared/VoertuigCard.cshtml
@model Voertuig

<div class="card card-outline-primary border-primary m-1 p-1">
	<div class="bg-faded p-1">
		<h4>
			@Model.Merk
			<span class="badge bg-primary" style="float:right">
				@Model.MerkType
			</span>
		</h4>
	</div>
	<div class="card-text p-1">@Model.Bouwjaar - @Model.Km</div>
</div>

MVCVoertuig/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCVoertuig</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCVoertuig.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm bg-primary navbar-light">
            <a class="btn btn-primary link-warning" asp-controller="Home" asp-action="Index">Home</a>
            <a class="btn btn-primary link-warning" asp-controller="Voertuig" asp-
               action="Index">Voertuigen</a>
               <vc:header-menu></vc:header-menu>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; PXL - MVCVoertuig
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCVoertuig/Views/Voertuig/Create.cshtml
@model MVCVoertuig.Models.Voertuig

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Voertuig</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Merk" class="control-label"></label>
                <input asp-for="Merk" class="form-control" />
                <span asp-validation-for="Merk" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MerkType" class="control-label"></label>
                <input asp-for="MerkType" class="form-control" />
                <span asp-validation-for="MerkType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bouwjaar" class="control-label"></label>
                <input asp-for="Bouwjaar" class="form-control" />
                <span asp-validation-for="Bouwjaar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Km" class="control-label"></label>
                <input asp-for="Km" class="form-control" />
                <span asp-validation-for="Km" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VerkoopPrijs" class="control-label"></label>
                <input asp-for="VerkoopPrijs" class="form-control" />
                <span asp-validation-for="VerkoopPrijs" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="AanwezigInShowroom" /> @Html.DisplayNameFor(model => model.AanwezigInShowroom)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCVoertuig/Views/Voertuig/Index.cshtml
@model IEnumerable<Voertuig>
@{
	ViewData["Title"] = "Index";
}

<p>
	<a asp-action="Create">Create new</a>
</p>

@foreach(var voertuig in Model)
{
	<partial name="VoertuigCard" model="voertuig" />
}

MVCVoertuig/Views/Voertuig/Merk.cshtml
@model IEnumerable<Voertuig>
@{
    ViewData["Title"] = "Merk";
    var merk = ViewBag.Merk;
}

<br />
<car-info merk="@merk"></car-info>